version: "3"

services:
  proxy:
    image: traefik
    restart: unless-stopped
    networks:
      proxy:
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./configurations:/configurations
    labels:
      traefik.enable: true
      traefik.docker.network: proxy

      traefik.http.routers.traefik-local.rule: Host(`traefik.local`)
      traefik.http.routers.traefik-local.entrypoints: https        
      traefik.http.routers.traefik-local.service: api@internal      

networks:
  proxy:
    external: true

