api:
  dashboard: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https

  https:
    address: :443
    http:
      tls: true
      middlewares:
        - secureHeaders@file
#  sieve:
#    address: :4190

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    usebindportip:  true
    network: proxy
  file:
    directory: /configurations

log:

  # Log level
  #
  # Optional
  # Default: "ERROR"
  #
  #filePath: /configurations/traefik.log
  #level: INFO

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  format: common
  
accessLog:

  # Sets the file path for the access log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary.
  #
  # Optional
  # Default: os.Stdout
  #
  # filePath = "/path/to/log/log.txt"
  filePath: /var/log/access.log

  # Format is either "json" or "common".
  #
  # Optional
  # Default: "common"
  #
  format: common

  filters:
    statusCodes:
      - 400-499
  


