http:
  middlewares:
    secureHeaders:
      headers:
        #sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

